language: python
python:
  - "2.7"
  - "2.6"
env:
  - DJANGO=1.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - python setup.py test
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - janneke.janssen@gmail.com
    on_success: never
    on_failure: always
