language: python
python:
  - "2.7"
  - "2.6"
env:
  - DJANGO=1.4
script:
  - python setup.py install
  - python setup.py test
  - python runtests.py
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - janneke.janssen@gmail.com
    on_success: never
    on_failure: always